FROM debian
WORKDIR /opt/koboldai
COPY ./environments /opt/koboldai/environments
COPY ./install_requirements.sh /opt/koboldai
USER root
RUN apt update && apt install wget aria2 git bzip2 python3 python3-venv -y
RUN ./install_requirements.sh cuda;rm -rf ~/.cache/pip
RUN git clone https://github.com/db0/KoboldAI-Horde-Bridge /opt/koboldai/KoboldAI-Horde-Bridge
ENV PATH=/opt/conda/bin/:$PATH
