FROM ebolam/koboldai_base
EXPOSE 5000/tcp
ENV remote=true
ENV quiet=true
ENV override_delete=true
ENV override_rename=true
ENV update=true
COPY . /opt/koboldai
WORKDIR /opt/koboldai/KoboldAI-Horde/
RUN git pull
WORKDIR /opt/koboldai/
CMD ./docker-standalone/docker-helper.sh