FROM ebolam/koboldai_base
EXPOSE 5000/tcp
ENV remote=true
ENV quiet=true
ENV override_delete=true
ENV override_rename=true
ENV update=true
RUN apt-get install python3 python3-venv -y
RUN python3 -m venv /opt/koboldai/KoboldAI-Horde/venv
COPY ./KoboldAI-Horde/requirements.txt /opt/koboldai/KoboldAI-Horde/
RUN /opt/koboldai/KoboldAI-Horde/venv/bin/pip install -r /opt/koboldai/KoboldAI-Horde/requirements.txt
COPY . /opt/koboldai
CMD ./docker-standalone/docker-helper.sh