FROM ebolam/koboldai_base
EXPOSE 5000/tcp
ENV remote=true
ENV quiet=true
ENV override_delete=true
ENV override_rename=true
ENV update=true
COPY . /opt/koboldai
CMD ./docker-standalone/docker-helper.sh