# This dockerfile is meant to serve as a rocm base image.  It registers the debian rocm package repository, and
# installs the rocm-dev package.


FROM ebolam/koboldai_base
WORKDIR /content/
RUN micromamba update -y -n base -f /content/environments/huggingface.yml
