# This dockerfile is meant to serve as a rocm base image.  It registers the debian rocm package repository, and
# installs the rocm-dev package.

FROM mambaorg/micromamba
WORKDIR /content/
COPY . /content/
RUN ls
RUN micromamba install -y -n base -f /content/environments/finetuneanon.yml
USER root
RUN apt update && apt install xorg -y
CMD python aiserver.py